from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "413cb054d8e5"
down_revision: Union[str, Sequence[str], None] = "5d1be60109b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "created_at")
    # ### end Alembic commands ###
