from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "25dfa479400a"
down_revision: Union[str, Sequence[str], None] = "e12882e2d3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dca_cycles", sa.Column("current_tp_price", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dca_cycles", "current_tp_price")
    # ### end Alembic commands ###
