from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e12882e2d3d8"
down_revision: Union[str, Sequence[str], None] = "3ce37d37cd09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_configs", sa.Column("trailing_enabled", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "bot_configs", sa.Column("trailing_callback_pct", sa.Float(), nullable=False)
    )
    op.add_column(
        "bot_configs", sa.Column("trailing_min_profit_pct", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_configs", "trailing_min_profit_pct")
    op.drop_column("bot_configs", "trailing_callback_pct")
    op.drop_column("bot_configs", "trailing_enabled")
    # ### end Alembic commands ###
