from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '707aef8d7291'
down_revision: Union[str, Sequence[str], None] = '99a944ebcc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'created_at')
    # ### end Alembic commands ###
