from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "99a944ebcc95"
down_revision: Union[str, Sequence[str], None] = "25dfa479400a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_configs", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("bot_configs_user_id_index"), "bot_configs", ["user_id"], unique=False
    )
    op.create_foreign_key(
        op.f("bot_configs_user_id_foreign"), "bot_configs", "users", ["user_id"], ["id"]
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_constraint(op.f("users_email_unique"), "users", type_="unique")
    op.create_index(op.f("users_email_index"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("users_email_index"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_unique"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "created_at")
    op.drop_constraint(
        op.f("bot_configs_user_id_foreign"), "bot_configs", type_="foreignkey"
    )
    op.drop_index(op.f("bot_configs_user_id_index"), table_name="bot_configs")
    op.drop_column("bot_configs", "user_id")
    # ### end Alembic commands ###
