from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a52a2f689402"
down_revision: Union[str, Sequence[str], None] = "413cb054d8e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dca_cycles", sa.Column("accumulated_dust", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dca_cycles", "accumulated_dust")
    # ### end Alembic commands ###
