from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ce37d37cd09'
down_revision: Union[str, Sequence[str], None] = 'a52a2f689402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dca_cycles', sa.Column('trailing_active', sa.Boolean(), nullable=False))
    op.add_column('dca_cycles', sa.Column('max_price_tracked', sa.Float(), nullable=True))
    op.add_column('dca_cycles', sa.Column('trailing_activation_price', sa.Float(), nullable=True))
    op.add_column('dca_cycles', sa.Column('trailing_activation_time', sa.DateTime(), nullable=True))
    op.add_column('dca_cycles', sa.Column('emergency_exit', sa.Boolean(), nullable=False))
    op.add_column('dca_cycles', sa.Column('emergency_exit_reason', sa.String(), nullable=True))
    op.add_column('dca_cycles', sa.Column('emergency_exit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dca_cycles', 'emergency_exit_time')
    op.drop_column('dca_cycles', 'emergency_exit_reason')
    op.drop_column('dca_cycles', 'emergency_exit')
    op.drop_column('dca_cycles', 'trailing_activation_time')
    op.drop_column('dca_cycles', 'trailing_activation_price')
    op.drop_column('dca_cycles', 'max_price_tracked')
    op.drop_column('dca_cycles', 'trailing_active')
    # ### end Alembic commands ###
